name: Daily NHL Projections

on:
  schedule:
    - cron: "0 13 * * *"   # Runs every day at 9AM EST (13:00 UTC)
  workflow_dispatch:        # Allows you to trigger manually

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run projections
      env:
        GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      run: |
        python main.py
