name: Update NHL ADP CSVs

on:
  schedule:
    - cron: "0 11 * * *"  # 11:00 UTC = 7:00 AM America/Detroit
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        env:
          ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }}
        run: |
          python main.py

      - name: Commit & push CSVs
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto-update CSVs"
          file_pattern: data/*.csv
